postgres_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: psql-dataplatform-mvp-41a5.postgres.database.azure.com
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_SECRET') }}"
      port: 5432
      dbname: postres
      schema: dbt
      threads: 4
